<script type="application/json" id="kgg-source-truth">
{
  "schema": 1,
  "app": "KGG Plan",
  "activeFixes": [
    "embedded-source-truth",
    "patch-retention-guard",
    "rollback-v023-debug-breakage",
    "phone-viewport-state-leak-guard",
    "phone-plan-local-list-drag",
    "local-content-no-auto-redirect",
    "no-auto-release-navigation",
    "release-center-local-fallback",
    "structured-textblock-parser",
    "free-textfield-units",
    "schmerz-tag-textblocks",
    "native-sync-diagnostics",
    "device-sync-menu-separation",
    "ui-mini-series",
    "phone-dock-anchored-correction",
    "tablet-card-reorder",
    "phone-liquid-actions",
    "phone-drawer-bank-align",
    "tablet-runtime-viewport-guard",
    "phone-landscape-tablet-menu",
    "encoding-guard-repair",
    "symbol-encoding-hotfix",
    "phone-ui-mini-fix",
    "android-qr-pdf-bridge",
    "pdf-plan-thumbnails",
    "ui-tablet-stability",
    "patient-qr-latest-base",
    "colleague-share-apk-update-fix",
    "patient-qr-root-query",
    "grossdruck-pdf-readable-images",
    "grossdruck-readability-beta",
    "059-ui-scaler-push-canary",
    "tablet-html-release-label",
    "cross-app-live-qr-camera",
    "tablet-recent-package-shell-geometry",
    "changelog-archive-window",
    "typed-update-versions",
    "source-control-char-guard",
    "plan-text-live-master-guard",
    "plan-text-boot-restore",
    "plan-text-recovery-finalize",
    "tablet-package-save",
    "pdf-global-exercise-numbering",
    "qr-full-plan-device-ladder",
    "therapy-cockpit",
    "therapy-cockpit-id-guard",
    "therapy-cockpit-start-link",
    "ticket-015-progressions",
    "ticket-015-live-fix"
  ],
  "currentVersion": {
    "versionCode": 87,
    "versionName": "1.0.87-ticket-015-live-fix",
    "lastPatchId": "kgg-v087-ticket-015-live-fix",
    "updatedBy": "kgg-module-scaffolder"
  },
  "latestPatchId": "kgg-v087-ticket-015-live-fix",
  "lastUpdateIntent": {
    "id": "kgg-v087-ticket-015-live-fix",
    "summary": "Make the progression editor bridge robust and keep variant metadata out of patient info text.",
    "touched": [
      "Admin-Editor",
      "Patienten-App"
    ],
    "notTouched": [
      "PDF",
      "QR/Patienten-App",
      "Scan/OCR",
      "Parser",
      "Plan-State",
      "Medien/Upload",
      "API-Key-Logik",
      "Android/APK",
      "GitHub Manifest",
      "Handy-Layout"
    ]
  }
}
</script>
