{
  "schema": 1,
  "output": "../index.html",
  "versionManifest": "../version.json",
  "sourceRoles": {
    "documentTitle": "document/base-shell.html",
    "runtimeIdentity": "runtime/base-runtime.html"
  },
  "requiredPatchIds": [
    "kgg-v041-ui-mini-series",
    "kgg-v042-phone-dock-anchored-correction",
    "kgg-v044-phone-liquid-actions",
    "kgg-v045-phone-drawer-bank-align",
    "kgg-v046-tablet-runtime-viewport-guard",
    "kgg-v050-phone-ui-mini-fix",
    "kgg-v051-android-qr-pdf-bridge",
    "kgg-v052-pdf-plan-thumbnails",
    "kgg-v053-ui-tablet-stability",
    "kgg-v060-tablet-html-release-label",
    "kgg-v061-cross-app-live-qr-camera",
    "kgg-v062-tablet-recent-package-shell-geometry",
    "kgg-v063-changelog-archive-window",
    "kgg-v064-typed-update-versions",
    "kgg-v065-source-control-char-guard"
  ],
  "parts": [
    "base-head.html",
    "metadata/source-truth.html",
    "metadata/changelog.html",
    "metadata/patch-rules.html",
    "metadata/changelog-guard.html",
    "document/base-shell.html",
    "runtime/base-runtime.html",
    "patches/v041-ui-mini-series.html",
    "patches/v042-phone-dock-anchored-correction.html",
    "patches/v044-phone-liquid-actions.html",
    "patches/v045-phone-drawer-bank-align.html",
    "patches/v046-tablet-runtime-viewport-guard.html",
    "patches/v050-phone-ui-mini-fix.html",
    "patches/v051-android-qr-pdf-bridge.html",
    "patches/v052-pdf-plan-thumbnails.html",
    "patches/v053-ui-tablet-stability.html",
    "patches/v060-tablet-html-release-label.html",
    "patches/v061-cross-app-live-qr-camera.html",
    "patches/v062-tablet-recent-package-shell-geometry.html",
    "patches/v063-changelog-archive-window.html",
    "patches/v064-typed-update-versions.html",
    "patches/v065-source-control-char-guard.html",
    "footer.html"
  ]
}
