const CACHE_NAME = 'kgg-handyplan-v23-media-bundle-runtime';
const COLLAPSE_SCRIPT = './collapse-cards.js?v=plan-update-label-1';
const START_SCAN_SCRIPT = './patient-start-scan.js?v=qr-camera-scan-1';
const MULTIPLAN_DB_SCRIPT = './patient-multiplan-db.js?v=local-exercise-db-1';
const CARD_SETTINGS_SCRIPT = './patient-card-settings.js?v=card-settings-pain-scale-1';
const DAY_HISTORY_SCRIPT = './patient-day-history.js?v=compact-history-1';
const MEDIA_SCRIPT = './patient-media-retry-cache_v2.js?v=media-bundle-runtime-5';
const UI_MICRO_POLISH_SCRIPT = './patient-ui-micro-polish.js?v=ui-micro-polish-1';
const APP_ASSETS = ['./','./index.html','./manifest.json','./icon.svg',COLLAPSE_SCRIPT,START_SCAN_SCRIPT,MULTIPLAN_DB_SCRIPT,CARD_SETTINGS_SCRIPT,DAY_HISTORY_SCRIPT,MEDIA_SCRIPT,UI_MICRO_POLISH_SCRIPT,'https://cdn.jsdelivr.net/npm/qrcode-generator@1.4.4/qrcode.js'];
function isIndexRequest(request){const url=new URL(request.url);if(url.origin!==self.location.origin)return false;return url.pathname.endsWith('/kgg/')||url.pathname.endsWith('/kgg/index.html')}
async function injectModules(response){try{let html=await response.clone().text();html=html.replace(/<script src="\.\/collapse-cards\.js[^"']*"><\/script>/g,'');html=html.replace(/<script src="\.\/numpad-ui-fix\.js[^"']*"><\/script>/g,'');html=html.replace(/<script src="\.\/patient-start-scan\.js[^"']*"><\/script>/g,'');html=html.replace(/<script src="\.\/patient-multiplan-db\.js[^"']*"><\/script>/g,'');html=html.replace(/<script src="\.\/patient-card-settings\.js[^"']*"><\/script>/g,'');html=html.replace(/<script src="\.\/patient-day-history\.js[^"']*"><\/script>/g,'');html=html.replace(/<script src="\.\/patient-media-retry-cache(?:_v2)?\.js[^"']*"><\/script>/g,'');html=html.replace(/<script src="\.\/patient-ui-micro-polish\.js[^"']*"><\/script>/g,'');html=html.replace('</body>','<script src="./collapse-cards.js?v=plan-update-label-1"></script><script src="./patient-start-scan.js?v=qr-camera-scan-1"></script><script src="./patient-multiplan-db.js?v=local-exercise-db-1"></script><script src="./patient-card-settings.js?v=card-settings-pain-scale-1"></script><script src="./patient-day-history.js?v=compact-history-1"></script><script src="./patient-media-retry-cache_v2.js?v=media-bundle-runtime-5"></script><script src="./patient-ui-micro-polish.js?v=ui-micro-polish-1"></script></body>');return new Response(html,{status:response.status,statusText:response.statusText,headers:{'Content-Type':'text/html; charset=utf-8','Cache-Control':'no-store, no-cache, must-revalidate'}})}catch(e){return response}}
self.addEventListener('install',event=>{event.waitUntil(caches.open(CACHE_NAME).then(cache=>cache.addAll(APP_ASSETS)).then(()=>self.skipWaiting()))});
self.addEventListener('activate',event=>{event.waitUntil(caches.keys().then(keys=>Promise.all(keys.filter(key=>key!==CACHE_NAME).map(key=>caches.delete(key)))).then(async()=>{await self.clients.claim();const clients=await self.clients.matchAll({type:'window',includeUncontrolled:true});clients.forEach(client=>client.postMessage({type:'APP_UPDATE_READY'}))}))});
self.addEventListener('fetch',event=>{if(event.request.method!=='GET')return;if(isIndexRequest(event.request)){event.respondWith(fetch(event.request,{cache:'no-store'}).then(async response=>{const copy=response.clone();caches.open(CACHE_NAME).then(cache=>cache.put('./index.html',copy)).catch(()=>{});return injectModules(response)}).catch(async()=>{const cached=await caches.match('./index.html');return cached?injectModules(cached):Response.error()}));return}const url=new URL(event.request.url);if(url.pathname.endsWith('/collapse-cards.js')||url.pathname.endsWith('/numpad-ui-fix.js')||url.pathname.endsWith('/patient-start-scan.js')||url.pathname.endsWith('/patient-multiplan-db.js')||url.pathname.endsWith('/patient-card-settings.js')||url.pathname.endsWith('/patient-day-history.js')||url.pathname.endsWith('/patient-media-retry-cache_v2.js')||url.pathname.endsWith('/patient-ui-micro-polish.js')){event.respondWith(fetch(event.request,{cache:'no-store'}).then(response=>{const copy=response.clone();caches.open(CACHE_NAME).then(cache=>cache.put(event.request,copy)).catch(()=>{});return response}).catch(()=>caches.match(event.request)));return}event.respondWith(caches.match(event.request).then(cached=>{if(cached){fetch(event.request).then(response=>{const copy=response.clone();caches.open(CACHE_NAME).then(cache=>cache.put(event.request,copy)).catch(()=>{})}).catch(()=>{});return cached}return fetch(event.request).then(response=>{const copy=response.clone();caches.open(CACHE_NAME).then(cache=>cache.put(event.request,copy)).catch(()=>{});return response}).catch(()=>caches.match('./index.html'))}))});
