#!/usr/bin/env node
"use strict";
const fs=require("fs"),http=require("http"),path=require("path"),{chromium}=require("playwright");
const root=path.resolve(__dirname,"..");
function assert(x,m){if(!x)throw new Error(m)}
function encPlan(plan){return Buffer.from(JSON.stringify(plan),"utf8").toString("base64url")}
function typeFor(f){return f.endsWith(".html")?"text/html; charset=utf-8":f.endsWith(".js")?"text/javascript; charset=utf-8":f.endsWith(".json")?"application/json; charset=utf-8":f.endsWith(".png")?"image/png":"application/octet-stream"}
function fileFor(urlPath){const rel=decodeURIComponent(urlPath.split("?")[0]).replace(/^\/+/, "")||"index.html",target=path.resolve(root,rel);return target.startsWith(root)&&fs.existsSync(target)&&fs.statSync(target).isFile()?target:null}
async function clickPadKey(page,label){await page.locator("#pad .padGrid").getByRole("button",{name:label,exact:true}).click()}
async function enterValue(page,input,value,ok=true){await input.click();for(const c of String(value)){await clickPadKey(page,c==="."?",":c)}await page.locator(ok?"#pad .padOk":"#pad .padCancel").click()}
async function openCard(card){if(!(await card.evaluate(e=>e.classList.contains("kggOpen"))))await card.locator("h3").click()}
async function main(){const server=http.createServer((req,res)=>{const f=fileFor(req.url||"/");if(!f){res.statusCode=404;return res.end("404")}res.setHeader("Content-Type",typeFor(f));res.end(fs.readFileSync(f))});await new Promise(r=>server.listen(0,"127.0.0.1",r));const port=server.address().port;
 const vw=Number(process.env.KGG_VIEW_W||390),vh=Number(process.env.KGG_VIEW_H||844),browser=await chromium.launch({headless:true}),ctx=await browser.newContext({viewport:{width:vw,height:vh},hasTouch:true,isMobile:vw<760}),page=await ctx.newPage(),errors=[];page.on("pageerror",e=>errors.push(String(e)));
 try{const plan={i:"set-view-smoke",t:"KGG Plan",v:1,d:6,e:[["LR 3",3,"LR","kg","Wdh"],["LR 1",1,"LR","kg","Wdh"],["LR 2",2,"LR","kg","Wdh"],["B 4",4,"B","kg","Wdh"]]},payload="KGGH2:"+encPlan(plan);await page.addInitScript(()=>localStorage.removeItem("kggPatientSetViewModeV1"));await page.goto("http://127.0.0.1:"+port+"/?plan="+encodeURIComponent(payload),{waitUntil:"networkidle"});await page.waitForFunction(()=>document.body.classList.contains("kggAlwaysCollapsed"));
  const sw=page.locator("#kggSetViewSwitch");await sw.waitFor({state:"visible"});assert(await sw.getAttribute("role")==="switch","view control is not a switch");assert(await sw.getAttribute("aria-checked")==="true","compact view is not default");const headGeom=await sw.evaluate(el=>{const b=el.getBoundingClientRect(),c=el.closest(".card").getBoundingClientRect();return{w:b.width,h:b.height,inside:b.left>=c.left&&b.right<=c.right&&b.top>=c.top&&b.bottom<=c.bottom}});assert(headGeom.h>=44&&headGeom.inside,"header switch geometry invalid: "+JSON.stringify(headGeom));
  const cards=page.locator("#list .ex");await openCard(cards.nth(0));const first=cards.nth(0);assert(await first.locator(":scope > .set").count()===3,"LR3 compact set count wrong");assert(await first.locator(".set .kggSideR").count()===3,"missing Re rows");assert(await first.locator(".set .kggSideL").count()===3,"missing Li rows");const order=await first.locator(".set").first().evaluate(set=>{const r=set.querySelector(".kggSideR").getBoundingClientRect(),l=set.querySelector(".kggSideL").getBoundingClientRect();return{rTop:r.top,lTop:l.top}});assert(order.rTop<order.lTop,"Re is not above Li");
  let reA=first.locator(".set").nth(0).locator(".kggSideR input.num").nth(0),reB=first.locator(".set").nth(0).locator(".kggSideR input.num").nth(1);await reA.click();await page.locator("#kggPadPair").waitFor({state:"visible"});await clickPadKey(page,"2");await clickPadKey(page,"5");await page.locator('#kggPadPair [data-kgg-key="b"]').click();assert(await reA.inputValue()==="25","kg not committed on pair switch");await clickPadKey(page,"1");await clickPadKey(page,"2");await page.locator("#pad .padOk").click();assert(await reB.inputValue()==="12","Wdh not committed");
  const liA=first.locator(".set").nth(0).locator(".kggSideL input.num").nth(0),liB=first.locator(".set").nth(0).locator(".kggSideL input.num").nth(1);await liA.click();await clickPadKey(page,"2");await clickPadKey(page,"0");await page.locator('#kggPadPair [data-kgg-key="b"]').click();await clickPadKey(page,"1");await clickPadKey(page,"0");await page.locator("#pad .padOk").click();assert(await liA.inputValue()==="20"&&await liB.inputValue()==="10","Li pair input failed");
  const re2A=first.locator(".set").nth(1).locator(".kggSideR input.num").nth(0);await enterValue(page,re2A,"1,5",false);assert(await re2A.inputValue()==="","cancel saved a value");await enterValue(page,re2A,"27,5",true);assert(await re2A.inputValue()==="27,5","decimal value failed");
  await sw.click();assert(await sw.getAttribute("aria-checked")==="false","legacy switch failed");assert(await reA.inputValue()==="25"&&await reB.inputValue()==="12"&&await liA.inputValue()==="20","values changed switching to legacy");await reA.click();assert(await page.locator("#kggPadPair").count()===0,"compact pair leaked into legacy");await page.locator("#pad .padGrid").getByRole("button",{name:"⌫",exact:true}).click();await page.locator("#pad .padGrid").getByRole("button",{name:"⌫",exact:true}).click();await clickPadKey(page,"3");await clickPadKey(page,"0");await page.locator("#pad .padOk").click();assert(await reA.inputValue()==="30","legacy edit failed");await sw.click();assert(await sw.getAttribute("aria-checked")==="true","compact switch back failed");assert(await reA.inputValue()==="30","legacy edit not visible in compact");
  await page.reload({waitUntil:"networkidle"});await page.waitForFunction(()=>document.body.classList.contains("kggAlwaysCollapsed"));assert(await page.locator("#kggSetViewSwitch").getAttribute("aria-checked")==="true","compact preference lost on reload");const firstReload=page.locator("#list .ex").nth(0);await openCard(firstReload);assert(await firstReload.locator(".set").nth(0).locator(".kggSideR input.num").nth(0).inputValue()==="30","legacy edit lost on reload");assert(await firstReload.locator(".set").nth(1).locator(".kggSideR input.num").nth(0).inputValue()==="27,5","decimal value lost on reload");assert(await firstReload.locator(".set").nth(0).locator(".kggSideL input.num").nth(0).inputValue()==="20","Li value lost on reload");
  for(const pair of [[1,1],[2,2],[3,4]]){const c=page.locator("#list .ex").nth(pair[0]);await openCard(c);assert(await c.locator(":scope > .set").count()===pair[1],"set count "+pair[1]+" wrong")}assert(await page.locator("#list .ex").nth(3).locator(".kggSideR,.kggSideL").count()===0,"B exercise got fake sides");const geom=await page.evaluate(()=>({scrollWidth:document.documentElement.scrollWidth,clientWidth:document.documentElement.clientWidth}));assert(geom.scrollWidth<=geom.clientWidth+1,"horizontal page overflow");assert(errors.length===0,"page errors: "+errors.join(" | "));
  await openCard(page.locator("#list .ex").nth(0));const shot=path.join(root,".tmp","patient-set-view-"+vw+"x"+vh+".png");fs.mkdirSync(path.dirname(shot),{recursive:true});await page.screenshot({path:shot,fullPage:true});console.log(JSON.stringify({status:"PASS",viewport:vw+"x"+vh,defaultCompact:true,sharedState:true,legacyRoundtrip:true,li:true,cancel:true,decimal:true,lr3:true,b4:true,noOverflow:true,screenshot:shot}));
 }finally{await ctx.close();await browser.close();await new Promise(r=>server.close(r))}
}
main().catch(e=>{console.error("KGG patient set-view smoke FAIL: "+(e.stack||e.message));process.exitCode=1});