#!/usr/bin/env python3
"""Publish incoming/kgg-next.html to kgg-update/ for the Android WebView wrapper."""

from __future__ import annotations

import hashlib
import json
import shutil
from datetime import datetime, timezone
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
INCOMING_HTML = ROOT / "incoming" / "kgg-next.html"
UPDATE_DIR = ROOT / "kgg-update"
UPDATE_HTML = UPDATE_DIR / "index.html"
VERSION_JSON = UPDATE_DIR / "version.json"


def fail(message: str) -> None:
    raise SystemExit(f"ERROR: {message}")


def sha256_file(path: Path) -> str:
    h = hashlib.sha256()
    with path.open("rb") as f:
        for chunk in iter(lambda: f.read(1024 * 1024), b""):
            h.update(chunk)
    return h.hexdigest()


def load_old_version_code() -> int:
    if not VERSION_JSON.exists():
        return 0
    try:
        data = json.loads(VERSION_JSON.read_text(encoding="utf-8"))
        return int(data.get("versionCode", 0))
    except Exception:
        return 0


def main() -> None:
    if not INCOMING_HTML.exists():
        fail("incoming/kgg-next.html fehlt. Keine Veröffentlichung möglich.")

    if INCOMING_HTML.stat().st_size <= 0:
        fail("incoming/kgg-next.html ist leer. Veröffentlichung gestoppt.")

    UPDATE_DIR.mkdir(parents=True, exist_ok=True)
    shutil.copyfile(INCOMING_HTML, UPDATE_HTML)

    published_sha = sha256_file(UPDATE_HTML)
    if not published_sha:
        fail("SHA-256 konnte nicht berechnet werden.")

    version_code = load_old_version_code() + 1
    stamp = datetime.now(timezone.utc).strftime("%Y-%m-%d-%H%M")

    manifest = {
        "versionCode": version_code,
        "versionName": f"html-update-{stamp}",
        "indexUrl": "index.html",
        "sha256": published_sha,
        "notes": "Auto-published from incoming/kgg-next.html. Generated by scripts/publish_kgg_update.py.",
    }
    VERSION_JSON.write_text(json.dumps(manifest, indent=2, ensure_ascii=False) + "\n", encoding="utf-8")

    verify_sha = sha256_file(UPDATE_HTML)
    if verify_sha != manifest["sha256"]:
        fail(f"SHA mismatch after publish: {verify_sha} != {manifest['sha256']}")

    print(f"Published {UPDATE_HTML.relative_to(ROOT)}")
    print(f"versionCode={version_code}")
    print(f"sha256={published_sha}")


if __name__ == "__main__":
    main()
